-- 1.
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT
WHERE DEPARTMENT_NO = 002
ORDER BY ENTRANCE_DATE ASC;

-- 2.
SELECT PROFESSOR_NAME, PROFESSOR_SSN
FROM TB_PROFESSOR
WHERE PROFESSOR_NAME NOT LIKE('___');

-- 3.
SELECT PROFESSOR_NAME AS , 2021 - CONCAT(19,SUBSTR(PROFESSOR_SSN,1,2)) AS 나이
FROM TB_PROFESSOR
ORDER BY 2021 - CONCAT(19,SUBSTR(PROFESSOR_SSN,1,2)) ASC;

-- 4.
SELECT SUBSTR(PROFESSOR_NAME,2,2) AS 이름
FROM TB_PROFESSOR;

-- 5. 
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE)- CONCAT(19,SUBSTR(STUDENT_SSN,1,2)) >= 20;

-- 입학당시 20살 이상이었나?
-- 주민번호에서 앞자리 뽑아오고
-- 입학년도에서 연도 뽑아와서


-- 6.
SELECT TO_CHAR(TO_DATE('2020/12/25'),'DAY')
FROM DUAL;


-- 7.
 -- TO_DATE('99/10/11','YY/MM/DD') -> 2099/10/11
 -- TO_DATE('49/10/11','YY/MM/DD') -> 2049/10/11

 -- TO_DATE('99/10/11','RR/MM/DD')  -> 1999/10/11
-- TO_DATE('49/10/11','RR/MM/DD')  ->  2049/10/11


-- 8.
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT
WHERE SUBSTR(STUDENT_NO,1,1) != 'A';

-- 9.
SELECT ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO ='A517178';

-- 10.
SELECT DEPARTMENT_NO AS 학과번호 , CAPACITY AS "학생수(명)"
FROM TB_DEPARTMENT;

-- 11.
SELECT COUNT(*)
FROM TB_STUDENT
WHERE COACH_PROFESSOR_NO IS NULL;

-- 12.
SELECT DISTINCT SUBSTR(TERM_NO,1,4) AS 년도, ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;

-- 13.
SELECT D.DEPARTMENT_NO,COUNT( DECODE(ABSENCE_YN,'Y',1))
FROM TB_DEPARTMENT D RIGHT OUTER JOIN TB_STUDENT S ON D.DEPARTMENT_NO = S.DEPARTMENT_NO
GROUP BY D.DEPARTMENT_NO
ORDER BY 1;
-- WHERE로 값을 분기하면 NULL이 생기지 않는다!
-- COUNT 내부에는 DECODE가 들어갈수 있고 그걸로 분기처리해서 원하는 값이면
-- COUNT 증가할수있도록 1이 나오게 하면
-- 원하는 값은 1이 증가해서 나오고
-- 값이 없으면 NULL->0이 나온다.

-- 14.
SELECT STUDENT_NAME, COUNT(STUDENT_NAME)
FROM TB_STUDENT
GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME)>=2
ORDER BY COUNT(STUDENT_NAME) DESC;
-- 그룹함수의 조건식은 HAVING 사용하자.


-- 15.
SELECT SUBSTR(TERM_NO,1,4) AS 년도, SUBSTR(TERM_NO,5,2) AS 학기, ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE
WHERE STUDENT_NO = 'A112113'
GROUP BY ROLLUP(SUBSTR(TERM_NO,1,4),SUBSTR(TERM_NO,5,2))
ORDER BY 1;

